# Generated by Django 6.0.3 on 2026-03-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_patientprofile_medical_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/doctors/'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/patients/'),
        ),
    ]
